import type { Metadata } from "next";
import {  Gotu, Playfair_Display, Poppins } from "next/font/google";
import "./globals.css";
import Providres from "./Providres";
import { cn } from "@/lib/utils";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const manrope = Gotu({
  subsets: ["latin"],
  variable: "--font-gotu",
  weight: ["400"],
});

const poppins = Poppins({
  subsets: ["latin"],
  variable: "--font-poppins",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

const playfair = Playfair_Display({
  subsets: ["latin"],
  variable: "--font-playfair",
  weight: ["400", "500", "600", "700", "800", "900"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          "theme-custom flex min-h-screen bg-[#070707] font-poppins text-[#FBEAD2] antialiased",
          manrope.variable,
          poppins.variable,
          playfair.variable
        )}
      >
        <Providres>{children}</Providres>
      </body>
    </html>
  );
}
